### ISSUE TITLE
strip slashes from the end of generated url

### ISSUE THREAD

**Issue by xrado** [QubitProducts/cherrytree#128]
Hi,

I'll continue the discussion here.

I found out that my fix breaks url generation for / (root), it strips out the only slash so it becomes empty string. I have also tested what actually happens on /path//// and I get an error "TypeError: Cannot read property 'options' of undefined" ..I didn't found yet from where it comes.

**Comment by KidkArolis** [comment]
I've continued the implementation and discussion in https://github.com/QubitProducts/cherrytree/pull/150.
