### ISSUE TITLE
Handle url Entries 

### ISSUE THREAD

**Issue by DavidStrada** [QubitProducts/cherrytree#137]
Hey, 
- Why do I mean by Handle url entries ? e.g. you click on /about. Use browser push state and update the url so now we will have www.example.com/about, tried an configure to use push state while it does load the template doesn't "push" /about. How would you achieve this ? 
- I notice you have interceptLinks option if it's set to false just goes to 404. 
- Having the ability to share links it's what makes the web unique if I might use this word, Tom Dale has a really good article about it.
- If it's not possible, would you be interested on PR ? 

Thanks,
David

**Comment by KidkArolis** [comment]
Did you try running the examples, this library already behaves as you explain.

**Comment by KidkArolis** [comment]
Let me know if you have further questions on this, I can go into more detail answering.
