### ISSUE TITLE
Feature request: Ability to drag-and-drop images or to embed files

### ISSUE THREAD

**Issue by vatterspun** [QubitProducts/cherrytree#142]
Current behavior: need to manually add images and files via the **Edit** menu.

Requested behavior: add files/images by drag-and-drop.

Additional actions (if possible): 

* Images - should show up immediately, resized to fit in window (maybe with a right-click option to use the resize window available in the **Edit - Insert Image** operation

* Plain text - when a Plain Text node, should allow entry into the text pane or addition as a node if dragged into the node pane.

* RTF files - same as above but RTF.

* Other file types - appear as a simple icon with their file extension (as with an **Edit - Insert File**)

**Comment by KidkArolis** [comment]
Wrong repo, you probably want: https://github.com/giuspen/cherrytree

**Comment by vatterspun** [comment]
> Wrong repo

I'm under a pseudonym and that's still embarrassing.
