### ISSUE TITLE
query param with urlencoded newline breakes route detection

### ISSUE THREAD

**Issue by xrado** [QubitProducts/cherrytree#146]
/someroute?test=aaabbb ..works fine  
/someroute?test=aaa%0d%0abbb  ..don't, you get root page

**Comment by KidkArolis** [comment]
Can't reproduce this issue. I tried reproducing in the `examples/vanilla-blog` project, but this query param works as expected and the routing works as expected:

![image](https://cloud.githubusercontent.com/assets/324440/20246762/f72474c8-a9b5-11e6-9866-215d805149f1.png)

Please provide more details if you're still have this issue.
