### ISSUE TITLE
Clarify Route Nesting example in the guide

### ISSUE THREAD

**Issue by blikblum** [QubitProducts/cherrytree#147]
In https://github.com/QubitProducts/cherrytree/blob/master/docs/intro.md#route-nesting describes that the routes inbox and mail does not have URL matches for it. But since there's no abstract option passed to then, technically they should be navigated to with e.g. /inbox and /inbox/m/:mailId

Also, i could not find the explanation of usage of  route name with a dot (mail.raw).

**Comment by KidkArolis** [comment]
Good catch!

I've now fixed the table in the guide and added explanation about the dotted route names here https://github.com/QubitProducts/cherrytree/blob/master/docs/api.md#default-path.

TBH, the dotted route names are too obscure and I might remove those in the next major version.
