### ISSUE TITLE
Saucelabs build is failing

### ISSUE THREAD

**Issue by blikblum** [QubitProducts/cherrytree#157]
Saucelabs build is failing for ie9 / 10/ 11

Probably related for #152 or #153 , since fails started at 22november

I could not figure what test is causes the fail.

If you figure where is fail root, i will be glad to provide a fix

Anyway, having time will test with IE locally ASAP

**Comment by blikblum** [comment]
Just ran test suite using IE 11 on Windows 10 with success, although is failing at SauceLabs:

```
26 11 2016 11:05:25.177:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
26 11 2016 11:05:25.204:INFO [launcher]: Starting browser IE
26 11 2016 11:05:25.974:INFO [IE 11.0.0 (Windows 10 0.0.0)]: Connected on socket nUIJ4LWYtpGtCEUgAAAA with id 13719555
IE 11.0.0 (Windows 10 0.0.0): Executed 48 of 49 (skipped 1) SUCCESS (0.415 secs / 0.248 secs)

```

I than build jquery-hello-world: it runs in edge but fails in IE11 with Promise not defined 

Not sure what's going

**Comment by KidkArolis** [comment]
I all works, it's just Saucelabs being dodgy as usual. And the image isn't updating... https://saucelabs.com/browser-matrix/cherrytree.svg
