### ISSUE TITLE
cherrytree abandoned?

### ISSUE THREAD

**Issue by xrado** [QubitProducts/cherrytree#166]
Hi @KidkArolis, I saw you released new router space-router. This means you wont work on  cherrytree anymore? ..just interested, because cherrytree is still my by far best router I worked with.
middleware, named routes, easy react integration ... really can't live without it anymore

**Comment by KidkArolis** [comment]
Heya, not abandoned, just you know, find very little time to work on it. Wanted to experiment with some simpler ideas, thus space-router. It is actually quite similar to cherrytree, but yeah, I can see how middleware, named routes, richer path matching is useful.

The fact that someone (you) is using it gives me more motivation to continue working on Cherrytree ;) So hopefully I'll be able to push that 3.0.0-alpha through. It's a biggish change and I'm slightly worried about making things worse, so will be very valuable to have someone (you) try it out.

Anyways, thanks for bringing this up. I hope my answer is satisfactory.

What's the biggest issue or feature you're missing in Cherrytree?

**Comment by xrado** [comment]
looking forward v3... currently can't remember any big issue with the router, maybe one that I already mention you, pushState with ability to set hash part of the url, but is not a big deal

yeah, let me know when u have 3.0.0-alpha, I can help test it out

**Comment by xrado** [comment]
maybe and option to add/update routes dynamically, to support code splitting
