### ISSUE TITLE
Some issues with lists

### ISSUE THREAD

**Issue by zauberparacelsus** [QubitProducts/cherrytree#75]
Right now I'm trying out CherryTree as a possible replacement for Zim.  However, I have found two issues with it.

With every rich-text editing app I've tried, when at the front of an item in a bullet list (IE: the caret is before the text, but after the bullet and space), pressing tab will indent the bullet item's level.  CherryTree does not follow this pattern, and instead indents the text while leaving the bullet alone.  In order to indent the list item's level, you need to indent before the bullet.

The second issue is that when you are on a list item's line and press return, the indent level is not preserved.

So, if you had a list like this:
* One
  * Two
    * Three

And then hit return, the indentation level goes back to the first one, instead of matching the indent level of the third item.  So, you would get this:
* One
  * Two
    * Three
* Four

Instead of this:
* One
  * Two
    * Three
    * Four

These are the only main issues I have so far that I find problematic.  Of course, it is entirely possible that the real issue is that CherryTree doesn't support proper list indentation levels, in which case this bug report can be treated as a feature/enhancement request.

**Comment by zauberparacelsus** [comment]
Yeah, I'm quite sure now that CherryTree doesn't support list indentation levels.  When a list item has a lot of text and it overflows onto the next line, the next line's indent does not match the indentation level of the list.

**Comment by KidkArolis** [comment]
I think you've got the repos confused. This `cherrytree` is a clientside router - not a text editor.

**Comment by zauberparacelsus** [comment]
Okay, sorry to disturb then >.<

**Comment by KidkArolis** [comment]
Which project were you talking about?haven't seen another one called
cherrytree.

**Comment by zauberparacelsus** [comment]
I was referring to https://github.com/giuspen/cherrytree , which is a note-taking application.
