### ISSUE TITLE
Using HistoryLocation with pushState:true and root != "/" generates incorrect URLs

### ISSUE THREAD

**Issue by andrewhickey** [QubitProducts/cherrytree#76]
When using cherrytree.transitionTo() or generate() the root is appended twice. Seems to be that HistoryLocation.formatURL and LocationBar.update both add it.

Should HistoryLocation.formatURL return path unmodified if pushState is true?

**Comment by KidkArolis** [comment]
Thanks for reporting this.

I never had to use the root option myself and haven't had a good enough test coverage so never noticed this issue. I have a fix (I hope!), just need to figure out how to get the tests pass in IE9/Safari on CI.

The urls that get generated now still include the root, for example `router.generate('foo')` would return '/some-root/foo'. But clicking links containing root or directly calling `router.transitionTo('/some-root/foo')` gets handled correctly.

**Comment by andrewhickey** [comment]
Nice one, thanks!
