### ISSUE TITLE
Contextual route names

### ISSUE THREAD

**Issue by nathanboktae** [QubitProducts/cherrytree#83]
CherryTree requires route names to be unique. But when defining routes for cherrytree-for-knockout tests, using the familiar forum domain, I started out with something like this:

```javascript
route('forums', function() {
  route('index', forumList)
  route('item', { path: ':forumId' })
  route('threads', function() {
    route('index', { path: ':threadId' })
  })
})
```

CherryTree complained saying 'index' has been defined twice. My initial guess was that they were contextual, so internally the route names would be something like `forums.index`, `forums.threads.index`, etc.

I think this would be desirable overall. Thoughts? I know it's a breaking change, but if 2.0 is still alpha, it seems ok to do.

**Comment by KidkArolis** [comment]
The name generation used to work as you're describing in older versions of cherrytree. That's similar to how Ember's router works. In Ember (and old versions of cherrytree) you had 2 functions `route` and `resource` - route could not have children, but resource could. So you'd use them both in combination to nest and control how the names get created. I.e. the resource name was combined with the route name. But all of this created a lot of head scratching to a lot of people in my team - you had to explain what the difference between route and resource is, how names get combined automatically. Also, sometimes, the names just wouldn't be very meaningful, especially if you nest several times.

Now, what you're suggesting is a bit simpler, you just always concatenate all of the names, but you could then end up with really long names, e.g. 'app.property.dashboard.realtime'.

So the current solution gives you the control - if you want to have longer, explicit names, you can just name routes 'threads.index' or 'forums.threads.index', you can also name them 'forumsThreadsIndex' and so on. I think it's the simplest and most flexible option. You just name the route with whatever is appropriate to your app.

**Comment by nathanboktae** [comment]
Yeah makes sense now after that explanation and thinking about it again. It's simple enough to bring your own naming strategy and you have full control over it.
