### ISSUE TITLE
Use another CI besides Codeship

### ISSUE THREAD

**Issue by nathanboktae** [QubitProducts/cherrytree#86]
Codeship required me to sign up to see the CI results. I tried OAuth with GitHub, and it wanted access to my private repos, which I didn't want to do (I didn't want to sign up in the first place). So I create an account... and I still can't see the project.

Also I don't see a .yml for it, so it appears not to be .yml based.... I'd recommend Travis CI or Circle CI - both great.

Also are you using SauceLabs or something else for cross browser testing?

**Comment by KidkArolis** [comment]
Yeah, happy to switch to Travis. I am using SauceLabs - do you know is there away to hide the saucelabs token when setting up the Travis project?

**Comment by oliverwoodings** [comment]
http://docs.travis-ci.com/user/encryption-keys/

**Comment by nathanboktae** [comment]
[Yes](https://github.com/nathanboktae/q-xhr/blob/master/.travis.yml)

**Comment by KidkArolis** [comment]
Thanks, working on it

**Comment by KidkArolis** [comment]
Using both (for) now.

**Comment by oliverwoodings** [comment]
![](http://i.imgur.com/c7NJRa2.gif)

**Comment by nathanboktae** [comment]
Can you expose your sauce username? the reason is to [add a Sauce Labs badge that's clickable to see tests results](https://github.com/nathanboktae/cherrytree-for-knockout).

**Comment by KidkArolis** [comment]
Hm, I don't quite get sauce - under that username - I have more than one project. I probably need to create another user specifically for this project?

**Comment by nathanboktae** [comment]
When you signup for saucelabs, look for the "opensauce" account option. Choose wisely as I missed it for another account, and couldn't change my account type to it later.

Also they have a poor design where one account = one project. So you add multiple projects you need to create a "sub-account".

Interestingly the angular guys have their sauce access key [in plain text](https://github.com/angular/protractor/blob/94859efc0c89174d20ad9c06283146f1f7e1bd63/.travis.yml#L10).

**Comment by nathanboktae** [comment]
Just a followup - thanks for fixing this in d40ff83 ! I can see the test results and you have a nice shiny browser matrix badge.
