### ISSUE TITLE
Move to es5 introduced some breakage

### ISSUE THREAD

**Issue by KidkArolis** [QubitProducts/cherrytree#91]

**Comment by nathanboktae** [comment]
Looks like it got axed completely by using ES5. I did notice that you use `Object.assign` but it wasn't mentioned on the readme.

**Comment by KidkArolis** [comment]
Hm, the master is now ahead of what's released to npm. I'll try to release it as a new alpha/rc soon.

I only use Object.assign in karma.conf.js and should just work out of the box in latest versions of karma since it pollyfills it (I think).

How/where is it breaking for you?

**Comment by nathanboktae** [comment]
Oh you're right. It's not, I just thought it needed a documentation. (I'm polyfilling it anyways myself so I wouldn't have noticed).
